version: "3.8"

services:
  app:
    image: pastebox
    container_name: pastebox
    build:
      context: .
    ports:
      - '8075:8075'
    depends_on:
      - db

  db:
    container_name: mongodb
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user

    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user
    ports:
      - '8081:8081'

volumes:
  data:
networks:
  default:
    name: mongodb_network